### ISSUE TITLE
UserMulti does not create a multi user field on-Premises 2013 

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1023]
_From @dpalfery on January 12, 2016 17:9_

When provisioning a new Field in a Site or on a List  the UserMulti is created as a single user field. 

Server Farm on build 15.0.4719.1002

_Copied from original issue: SharePoint/PnP#1280_

**Comment by VesaJuvonen** [comment]
_From @kilasuit on January 12, 2016 17:35_

This has been a long lasting issue with the underlying CSOM  - not sure that its ever been resolved as is an engineering issue not an PnP issue see issue raised in the PnP-PowerShell Repo https://github.com/OfficeDev/PnP-PowerShell/issues/59

Also I spent hours refactoring and retrying to get this to work - but it just doesnt seem to be available unless its recently changed @VesaJuvonen @jansenbe - I'm not sure as I haven't been keeping a tab on the latest CSOM releases.

**Comment by VesaJuvonen** [comment]
_From @shurick81 on June 30, 2016 19:0_

Can anyone solve/investigate this?

**Comment by jansenbe** [comment]
We're covering UserMulti fields in our test runs which run OK for 2013/2016/Online (see https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/field_add.xml#L35). I assume the issue has been fixed in the engine, so will close this issue. Feel free to re-open if you can reproduce this using the approach shown in the test in combination with the latest version of the engine and CSOM redist
