### ISSUE TITLE
Global navigation set to inherit is ignored

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1079]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior

When the following is included in the template navigation should be inherited:

```
<pnp:GlobalNavigation NavigationType="Inherit">
</pnp:GlobalNavigation>

```
#### Observed Behavior
The following line ObjectNavigation doesn't seem to work:
```
case GlobalNavigationType.Inherit:
    navigationSettings.GlobalNavigation.Source = StandardNavigationSource.InheritFromParentWeb;
```

The navigation is never updated to inherited.
                               
#### Steps to Reproduce
Update a template.xml file to include:

```
<pnp:GlobalNavigation NavigationType="Inherit">
</pnp:GlobalNavigation>

```
Apply the template to a subsite.

**Comment by jansenbe** [comment]
Your fix has been merged in. Please verify with March release once available

**Comment by Simo9552** [comment]
Hello, 

The object navigation seems to work in the march release.

 var navSettings = new WebNavigationSettings(ctx, web);
 var taxSession = TaxonomySession.GetTaxonomySession(ctx);

  navSettings.GlobalNavigation.Source = StandardNavigationSource.InheritFromParentWeb;
 navSettings.CurrentNavigation.Source = StandardNavigationSource.PortalProvider;
                                             
 navSettings.Update(taxSession);
ctx.Load(navSettings);
 ctx.ExecuteQuery();

This results in the expected behaviour. 

Side note:  after settting the navigation to global , you set the current navigation to display sites, pages or siblings. When you update the current navigation it overwrites the global again.  

  AreaNavigationEntity nav = new AreaNavigationEntity();

  nav.CurrentNavigation.ShowSubsites = true;
  nav.CurrentNavigation.ShowPages = false;
  nav.CurrentNavigation.ShowSiblings = true;
                           
  web.UpdateNavigationSettings(nav);
   web.Update();
    web.Context.ExecuteQuery();

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
