### ISSUE TITLE
Default Calendar List provisioned with views that do not support recurrence

### ISSUE THREAD

**Issue by stevus1970** [SharePoint/PnP-Sites-Core#1104]
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
Possibly SP2016 and SP2013 - untried
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When provisioning a Calendar, the views should be able to support recurrent events.  I believe this is due to the settings required to support recurrence which (I think) are not currently part of the CSOM code and therefore a work-around might need to be considered or exclusion of views from Calendars (perhaps an explicit limitation).

#### Observed Behavior
The views, if the default ones are provisioned, do not support a recurrent event - the recurrent item appears as a single event starting at the start date and extending until the end date instead of the individual recurrences.

#### Steps to Reproduce
Extract a Calendar from a site using the PnP engine, and then provision.

Work-around: remove the pnp:Views element from a Calendar pnp:ListInstance and re-provision a new Calendar.

**Comment by jansenbe** [comment]
Thanks @stevus1970  for reporting this. Recurrence indeed is "special" case which requires some additional research first.

**Comment by XristophD** [comment]
Hey, I did some research today and had a Microsoft ticket open on that - recurrent list views are possible through CSOM Code. The **ViewTypeKind** is a flagged Enum, so you can combine them, e.g.: 
                    **ViewTypeKind = ViewType.Calendar | ViewType.Recurrence**

Creating views with this code displays recurrent items in the list properly. 
In the current Core Code the ViewTypeKind-Enum is parsed from a string and therefore it does not give the right values back, so it only translates as "Calendar" instead of "Calendar | Recurrence". 

The ListViewCreationInformation in Core would have to look like this for the type calendar: 

```
var viewCI = new ViewCreationInformation
                {
                    ViewFields = viewFields,
                    RowLimit = viewRowLimit, 
                    Paged = viewPaged,
                    Title = viewTitle,
                    Query = viewQuery.ToString(),
                    ViewTypeKind = ViewType.Calendar | ViewType.Recurrence
                    PersonalView = false,
                    SetAsDefaultView = viewDefault,
                };
```

A workaround would be to add "Recurrence" to all "Calendar" typed views, since Calendar should always be able to display recurrent items - or at least it doesn't hurt!?

Our customer is using recurrent items in Calendars a lot and therefore this item should be fixed soon. 
In the meantime, we just delete the default Calendar-View and create a new one. It seems that the ViewTypeKind can not be changed on an existing list view. 

The Code that I am referring to is in the Core -> Framework -> Provisioning -> ObjectHandler -> ObjectListInstance.cs in Row 376 where the viewTypeString is built - this should be the flagged enum, not a string.

**Comment by hyankov** [comment]
+1, this is a pretty high-impact issue, why is it not getting any attention? PnP is basically provisioning calendars with broken recurrence capability.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
