### ISSUE TITLE
Using Apply-PnPProvisioningTemplate with http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema

### ISSUE THREAD

**Issue by shurick81** [SharePoint/PnP-Sites-Core#1242]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[x] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
16.0.4534.1000

#### Expected or Desired Behavior
deployed template

#### Observed Behavior
[Apply-PnPProvisioningTemplate], NullReferenceException

#### Steps to Reproduce
Error occurs when I change schema reference from <pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
to <pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
I use Apply-PnPProvisioningTemplate.

**Comment by rgylesbedford** [comment]
The current version implemented is the 2016/05 version. https://github.com/SharePoint/PnP-Provisioning-Schema#current-implemented-version-in-the-pnp-provisioning-engine

**Comment by shurick81** [comment]
Any plan for implementing the 2017/05 version?

**Comment by stevebeauge** [comment]
I don't know the reasons to have separated the schema from the engine itself, but this is actually a big brake to contributing. The provisioning engine still lacks a lot of features and has some bunch of bug. 

Most of enhancements I'd try to implement are stopped because it requires to have the schema updated. And the update frequency is too low to be practical.

Any chance to increase release rate of schema updates ?
