### ISSUE TITLE
SharePointPnPCoreOnline dependency to System.Net.Http.Formatting and Microsoft.IdentityModel

### ISSUE THREAD

**Issue by tuandomvn** [SharePoint/PnP-Sites-Core#1287]
Hi all,

I've added SharePointPnPCoreOnline 2.16.1706" in .net core project version 1.0.0-* and it through 2 errors:
The dependency Microsoft.IdentityModel could not be resolved.
The dependency System.Net.Http.Formatting could not be resolved.

I think if SharePointPnPCoreOnline depends on those, it should be added to the project automatically. Please help to take a look.

Thanks

**Comment by Chipzter** [comment]
Hi tuandomvn,

I ran into the exact same issue today in an old 1.0.0-* project targeting net46. The only way I was able to add a reference to the PnP Nuget package was to download the source and remove those two dependencies from the .nuspec file and build my own nuget package. 

I assume these references are superfluous in recent versions of the .NET framework since Microsoft.IdentityModel has been moved into the framework since version 4.5 [ref](https://docs.microsoft.com/en-us/dotnet/framework/security/whats-new-in-wif) and System.Net.Http.Formatting is not a framework assembly but a part of the Microsoft.AspNet.WebApi.Client Nuget package [ref](https://github.com/aspnet/Home/issues/1132)

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
