### ISSUE TITLE
OfficeDevPnP.Core.Pages.ClientSidePage extend properties to include Name

### ISSUE THREAD

**Issue by kath561** [SharePoint/PnP-Sites-Core#1349]
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[ x Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
only page title currently available. Page name and title are supported separately in SharePoint GUI details pane and may not be the same value. It may be realistic to only support a get for the Name as a change to this is really a file rename which should perhaps be done explicitly. In order to show the file details in a list of links etc the Name property would be essential as the title cannot be relied upon to be the same. As a Url is not obviously supplied creating a click link would require the Name field. Supplying a Url property is another way of addressing this problem unless that is buried in the ListItem somewhere perhaps. 

 Sharing is caring.

**Comment by jansenbe** [comment]
Title is settable using object model in October version. Page renames is a different topic, since this needs to work on noscript enabled sites (like all the modern team sites) we can't use the classic "rename" api's to change the page name...there's internal API's for this, but these are not supported for external use an this moment, so for now you'll need to provide the final, correct, name when you save the client side page.
