### ISSUE TITLE
Provisioning Client Side Pages when Layout=Home, EnableComments=false doesn't work.

### ISSUE THREAD

**Issue by SteveClements** [SharePoint/PnP-Sites-Core#1571]
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Schema version 2018-01
In provisioning template xml for client side pages, when setting the Layout to be Home and EnableComments false, I'd expect comments to be disabled on the page created.

#### Observed Behavior
Comments are enabled.

#### Steps to Reproduce
```
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/01/ProvisioningSchema">
...
<pnp:ClientSidePages>
        <pnp:ClientSidePage PageName="ModernHome.aspx"
            PromoteAsNewsArticle="false" Overwrite="false"
            Publish="true" Layout="Home" EnableComments="false">
```

I'm running this using the PowerShell cmdlets. 
![image](https://user-images.githubusercontent.com/5147797/35917165-00020526-0c05-11e8-98d4-d25b16cdeacf.png)

**Comment by agamadrid** [comment]
Hi,

I'm seeing the same issue, the home page has banner & the comments are enabled.
When I check the page properties I can see that the page is created with the Article layout instead of using the home layout.

![image](https://user-images.githubusercontent.com/29859736/36901413-07949886-1e1f-11e8-97af-9d2442d19c92.png)

Can you please advice?
Regards,

**Comment by jansenbe** [comment]
This is fixed in the upcoming March release

**Comment by agamadrid** [comment]
Thanks, where can I check when that release is available?
Regards,

**Comment by jansenbe** [comment]
Updated nuget packages will appear this week. Chech twitter release coms or check on nuget site.

**Comment by agamadrid** [comment]
Hi,

I can see the banner when creating "home" layout page. has this been fixed in this release? Banner shouldn't be there for Home pages.

Thanks

![image](https://user-images.githubusercontent.com/29859736/37279925-2f6ab13e-25e4-11e8-9b2f-c9eb434ca082.png)

![image](https://user-images.githubusercontent.com/29859736/37279899-15f8e176-25e4-11e8-87ed-f8a9e7170471.png)

**Comment by jansenbe** [comment]
Can you set the layout to "Home" and try again?

**Comment by agamadrid** [comment]
Hi jansenbe.

I'm still seeing the banner. Same as above. I already have the Layout="Home".
If this should work, can you please post a sample of a home page that is correctly generated without the banner?
Thanks for your help & kind Regards,
