### ISSUE TITLE
The type or namespace name 'ClientRequestWrapper' could not be found (master branch)

### ISSUE THREAD

**Issue by cagdasdavulcu** [SharePoint/PnP-Sites-Core#2138]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I forked the PnP-Sites-Core Repository and  pulled to my local machine. I tried to compile the source code but it failed. (master branch. i didn't try to compile the source code of other branches)

#### Observed Behavior
I'm getting the following exception:
CS0246:	The type or namespace name 'ClientRequestWrapper' could not be found (are you missing a using directive or an assembly reference?)

#### Steps to Reproduce
- Get source code
- compile
- exception

**Comment by jansenbe** [comment]
Seems like it's picking up an older CSOM version that most likely sits in the GAC. Try cleaning your environment by installing the CSOM redists and then try again

**Comment by cagdasdavulcu** [comment]
Thank you very much for your feedback!

I have no CSOM assemblies in GAC. I think it is also not the preferred way.

There is by default a reference called SharePointPnP.Client. I thought, that this assembly is pulling needed csom assemblies dynamically on base of your build configuration. Because of that i didn't reference the csom assemblies manually.

After i referencing the CSOM assemblies manually, i could build the solution. Is this the way, how you setup the project?

thank you very much!

**Comment by jansenbe** [comment]
You need to use the OfficeDevPnP.Core.sln solution to build PnP

**Comment by cagdasdavulcu** [comment]
Thank you! :)

**Comment by jonathaneckman** [comment]
@jansenbe OfficeDevPnP.Core.sln build for .NET 4.5. The PnP-PowerShell project [contribution guidance](https://github.com/SharePoint/PnP-PowerShell#contributing) describes a post build process that only applies to their dotnet core build. This build depends on the dotnet core build of PnP Core. Any tips on how to build PnPCore.sln so that [the reference to your dotnet core build](https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/PnPPowerShell.csproj#L56) is valid? 

Or is the best course of action to build for .NET 4.5 and work with the PnP-PowerShell project team for guidance?
