### ISSUE TITLE
List forms on content types

### ISSUE THREAD

**Issue by PieterVeenstra** [SharePoint/PnP-Sites-Core#224]
I've got a list where a form has been specified on a content type of a list. As list content types are not exported these forms are also ignored. 

Should list content types be exported rather than assumed to be the same as the site collection version of the same content type? In this case content type references on a list don't seem to be the right solution.

**Comment by PaoloPia** [comment]
Hi Pieter,
Sorry for the delayed answer. In order to support the suggested scenario, aside from changing the engine, we should also change the XML schema. Thus, we cannot do that right now, but if you still need this capability, I ask you to create a new Issue in the schema repo (https://github.com/SharePoint/PnP-Provisioning-Schema/) so that I can keep track of this need while working on the upcoming next version of the provisioning schema. Thanks.

**Comment by jansenbe** [comment]
@erwinvanhunen recently added support for list content types. See https://github.com/SharePoint/PnP-Sites-Core/commit/824818507d557a50cba828e360a300fa592542dc. 

I'm closing this one now.

@PieterVeenstra : if you still can't realize your scenario using the latest dev build then let's open a new issue
