### ISSUE TITLE
Error on provisioning during content type "Value cannot be null.  Parameter name: s"

### ISSUE THREAD

**Issue by Kesudan** [SharePoint/PnP-Sites-Core#2246]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Observed Behavior
On provision content types have stopped being able to update or create for a couple of tenancies, but works on others.

Whilst I assume this to be a tenant based issue, wondered if anyone else had come across this and had any work around?

This occurs in the handler "ObjectContentType" when creating or updating a fairly simple content type.

Upon executing query at the end of the update or create method the following errors occur:

**Microsoft.SharePoint.Client.ServerException: Value cannot be null.  Parameter name: s**

This had been working fine for a while, but suddenly started occurring in the past couple of days.

**Comment by jansenbe** [comment]
Please upgrade to the latest version, there was a server side issue which currently is being fixed, but in the meantime, we've released an updated pnp core library that handles this issue.

**Comment by VesaJuvonen** [comment]
See following item for more details https://github.com/SharePoint/sp-dev-docs/issues/3947. If you update on the latest PnP version, we have provided a workaround until the in-product server side API fix will be fully rolled out by end of this week. If you cannot update to latest PnP version, you should be automatically fixed by end of Friday PDT as the server side issue in SPO is getting fully rolled out.
