### ISSUE TITLE
Fields / ContenTypes provisioning for subsites

### ISSUE THREAD

**Issue by Draggon** [SharePoint/PnP-Sites-Core#238]
Hi

I’m using PnP provisioning to backup / restore sites.
I’m curious why site Fields / ContenTypes are not supported for subsites - marked as “not a recommended practice”.
I have added this to code but above sentence suggest it won’t be merged to master 

I can find disadvantages for ContenTypes at this level but I think PnP should support this scenario and warn user.

Thanks

**Comment by PaoloPia** [comment]
Hi,
Thanks for using PnP. About your question, we do not encourage the usage of Fields and Content Types at the subweb level because you could easily loose control of your information architecture. Moreover, having fields and content types at the root site collection level allows you to share the same artifacts in all of the webs of the site collection, and to keep the search filtering capabilities (those based on content types and fields) much more clean and regulated. Last but not least, from a maintenance perspective it is much more easy to do maintenance of Fields and Content Types at the root level, rather than having to skim for them in the full hierarchy.
