### ISSUE TITLE
Issues with PnP provisioning

### ISSUE THREAD

**Issue by SabbeRubbish** [SharePoint/PnP-Sites-Core#2506]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Expected PnP source template to be exact at target location.

#### Observed Behavior
Following issues are occuring:
- Quick Launch menu has items twice in it
  - This is not the case in the template.xml - they are only there once
- Document library that has LIST content type "Document Set" renamed to something else still has name as "Document Set" - list name "Parlementaire vragen" 
  - I've noticed that this was not in the template either, so this was an error with Get-PnPProvioningTemplate cmdlet. (but bad design, I'm aware :-))
- LIST content type in previous bullet does not have custom fields and only has built-in fields (the fields are however available in the list)
  - Same here the custom LIST fields like "Datum", "Discipline_0" and "Status Parlementaire vraag" are in the list definition, and even used in the View correctly, but not added to the content type

#### Steps to Reproduce
Create new Unified Group
`New-UnifiedGroup -DisplayName "GDPB2" -Owner "admin@M365x241798.onmicrosoft.com" -Name "GDPB2"`
Activate site by navigating to Outlook and clicking on the O365 Group's "Files" link
`Connect-PnPOnline https://M365x241798.sharepoint.com/sites/gdpb2 -UseWebLogin`
`Apply-PnPProvisioningTemplate -Path $templateFile`
(see template.txt attached)
[template.txt](https://github.com/SharePoint/PnP-Sites-Core/files/3945054/template.txt)

**Comment by akashSharma2505** [comment]
@SabbeRubbish, I think I could help you so please find my responses as below.

1. Please set remove existing node property to "true" (<pnp:StructuralNavigation RemoveExistingNodes="true" />)
2. Could you please try to create the list structure manually in sharepoint site. I meant is, create custom list -> create custom content type and name it as per your requirement -> add the content type to this list -> Please download the template using GetPnnTemplate command in powershell. 
Now, check the difference between downloaded template file and your template. I hope you will find the difference will be able to do the correction in your template.

3. Similar to the previous point, I am expecting you will solution for this issue as well.

**Note : I could not understand 2 & 3 issue properly but the given solution could help you the identify the root cause**

**Comment by SabbeRubbish** [comment]
Hi akash,

Thanks for your reply.
I will try that! Thank you!
