### ISSUE TITLE
ObjectFiles is not passing the Folder to FileSystemConnector

### ISSUE THREAD

**Issue by larry-lau** [SharePoint/PnP-Sites-Core#371]
Current implementation assume all the file asset are organized flat in the root of the output folder.
The ObjectFile is not passing the Folder value to the container parameter.

`using (var stream = template.Connector.GetFileStream(file.Src))`

However, we have large number of display template and css, javascript files and we like to organized them in the same structure they would be SharePoint.  The problem for us is that even if we want to implement Custom FileSystemConnector, the container value is not available.  

I would be nice the folderName is passed like this and the FileSystemConnector.cs need to ignore it to maintain the current behavior to look only at the output folder.  

`using (var stream = template.Connector.GetFileStream(file.Src, folderName))`

Any other idea on how I can implement my own FileSystemConnector?  Or Should this be the default behavior? 

Once this is done, this will enable us to support exporting and importing files with folder structure from Style Library to address issue #365

**Comment by PaoloPia** [comment]
Hi,
Thanks for your patience. With the introduction of the .PNP OpenXML package format, we started to support hierarchies of files and folders. We also added support for subfolders with FileSystemConnector, in order to better support the export of workflow definitions. So, I suggest you to give a try to the new .PNP packaging to satisfy this kind of requirements. I will close this item in the meantime. Thanks.
