### ISSUE TITLE
CreateXmlNodeFromPageLayout should check for page layout's existence

### ISSUE THREAD

**Issue by arangas** [SharePoint/PnP-Sites-Core#382]
This is a bit of a nit pick but the current behaviour for calling something like `BrandingExtensions.SetAvailablePageLayouts()` gives a NullReferenceException if the page layout(s) don't exist.

It would be nice if there was a null check after the call to GetPageLayoutListItemByName() [in CreateXmlNodeFromPageLayout()](https://github.com/OfficeDev/PnP-Sites-Core/blob/a21e3680104f8be040e6401513f809b444b0baaf/Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs#L1282).

**Comment by PaoloPia** [comment]
Hi Alex,
So far we return a NullReferenceException because we assume that, if you are referencing a not existing page layout, we should make you aware of it instead of simply skipping that page layout, eventually moving to the next one in the list. Are there use cases in which you want/need to be able to reference not existing page layouts and still continue to process the request? Thanks.

**Comment by arangas** [comment]
Going back a bit in time here but I think what I meant is that a more "developer friendly" experience would be to check for the null and throw something like ArgumentException with the reason that it failed. I believe at the time it took me a while to find out what was going wrong involving downloading the source, debugging, etc..., which an explanatory exception would have avoided.

**Comment by PaoloPia** [comment]
Hi Alex,
Happy New Year! Got it and fixed with #917. I will close this item. Thanks.

**Comment by arangas** [comment]
Super, thanks!
