### ISSUE TITLE
Provisioning Engine: ListInstance FieldRef DisplayName not set correctly

### ISSUE THREAD

**Issue by paulpascha** [SharePoint/PnP-Sites-Core#498]
I've created a ProvisioningTemplate in XML. For some of my site columns I want to change the Display Name at the List Level. The Provisioning Schema allows me to specify a different DisplayName in FieldRef elements which are part of my ListInstance element, but the Display Names are not set correctly after applying the template for the first time. If I apply the Provisioning Template a second time, the values are correctly set.

**Comment by PaoloPia** [comment]
Hi Paul,
Are you still experiencing this issue? Thanks.

**Comment by jansenbe** [comment]
Internal test results:

Source:
- Created source xml with site column and list with updated display name site column field ref.

Success: Online and On-Prem
- Provisioned site column and list successfully and observed display name in list first provision itself.

Since testing showed success + we've a test covering this scenario (https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/list_add.xml#L91). 

So will close the issue.
