### ISSUE TITLE
Provisioning Pages : Web Part added not getting displayed in the wiki page

### ISSUE THREAD

**Issue by wizneeraj** [SharePoint/PnP-Sites-Core#545]
I have extended the code present in the ObjectPages.cs & ObjectPageContents.cs in the Provisioning framework's ObjectHandlers section. 
The extension done on the ObjectPageContents.cs is to extract all the pages and not only the home page.
Similarly, the extension done in ObjectPages.cs is to provision all the pages and not only the home page. On doing so, i found there is an issue in displaying the web part in the wiki page. 

If a web part with the same name is added in multiple pages, the web part is getting displayed only in the first page being provisioned and not in the other consecutive pages.

On examination, it was found that the line "item[fieldValue.Key] = parser.ParseString(fieldValue.Value);" in the ObjectPages.cs is causing the issue.

This is because of the following line of code which adds the token for the web part

var allWebParts = web.GetWebParts(url);
foreach (var webpart in allWebParts)
{
  parser.AddToken(new WebPartIdToken(web, webpart.WebPart.Title, webpart.Id));
}

Can there be a method to remove the token from the parser, so that after processing each page, the tokens added can be removed?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Actually, we do not support and we do not plan to support extraction of content pages. In order to do that, you should write a custom extensibility handler, instead of changing the engine itself. Aside from that, if you can submit a PR to apply the suggested changes (excluding the extraction of pages) we will be more than happy to evaluate it. In the mean time I will close this item. Thanks.
