### ISSUE TITLE
the parameter SiteCollectionTermGroup is not executing if true

### ISSUE THREAD

**Issue by KbWorks** [SharePoint/PnP-Sites-Core#643]
#### Category

[x] Bug
[ ] Enhancement
#### Environment

[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

the parameter SiteCollectionTermGroup is not executing if true
#### Observed Behavior

It create the termgroup in the termstore on tennant level instead of sitecollection level
#### Steps to Reproduce

my xml: <pnp:TermGroup Name="Site Collection - {parameter:O365TenantName}-sites-{parameter:SiteCollectionUrl}" Description="" SiteCollectionTermGroup="true">
 using applytemplate method it runs without error only provisioning the group on the wrong level.
I am using the 2015-12 schema.

using the may pnp core version 2.4.1605.0

maybe i am missing another parameter but seems a bug.

thanks in advance,

Paul

**Comment by PaoloPia** [comment]
Hi Paul,
Thanks for your feedback. In the latest builds of the engine we added support for token {sitecollectiontermgroupname} specifically for local Site Collection Term Groups. Please use that token instead of the one you are using. I've tested the creation of the local Site Collection Term Groups and it works properly, now. I will close this item, but feel free to let me know of any further issue related to this topic. Thanks.
