### ISSUE TITLE
Template is not valid: The required attribute 'StatusFieldName' is missing.

### ISSUE THREAD

**Issue by malexandrum** [SharePoint/PnP-Sites-Core#712]
#### Category

[x] Bug
[ ] Enhancement
#### Environment

[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013
#### Expected or Desired Behavior

Be able to get template from working site and apply it to new site collection
#### Observed Behavior

Created a template using the latest version of powershell commandlets (Aug release) from a site collection customized using features. Then trying to Apply-SPOProvisioningTemplate, in console I get:
`Apply-SPOProvisioningTemplate : The provided template is not valid!
At line:1 char:1
- Apply-SPOProvisioningTemplate -Path .\template.pnp
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], ApplicationException
  - FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate`

In SPTraceLog, I get:
`[Error]    Template is not valid: The required attribute 'StatusFieldName' is missing.`
#### Steps to Reproduce

1) Get-SPOProvisioningTemplate with only -Out parameter set to either xml or pnp file
2) Apply-SPOProvisioningTemplate -Path template.xml

**Comment by mrpullen** [comment]
Can confirm this is an issue with SharePoint 2013 environment as well. The only Handler I am using import / exporting is Workflows.

Seems to be resulting from the OfficePnp Schema

https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/f019a931b8d700135d7d7960f5bc0c7c9ab7b093/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2016-05.xsd

Line  3214

Here is what my pnp:WorkflowSubscription looks like

<pnp:WorkflowSubscription DefinitionId="4dc57b3c-3f53-4145-9ca9-c0a0c99e03da" ListId="{listid:testList}" Enabled="true" EventSourceId="{listid:testList}" WorkflowStartEvent="false" ItemAddedEvent="true" ItemUpdatedEvent="false" ManualStartBypassesActivationLimit="false" Name="Workflow">
            <pnp:PropertyDefinitions>
              <pnp:PropertyDefinition Key="StatusColumnCreated" Value="0" />
..

Guessing that since my workflow doesn't have a Status Column, but the schema expects it, that we have an issue.

Manually adding the StatusFieldName="WFStatus" seems to bypass that error, but then I have some additional work todo on the workflow properties..

**Comment by jansenbe** [comment]
@malexandrum and @mrpullen : can you please share the template that resulted in your errors. Will help troubleshooting. Thx.

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
