### ISSUE TITLE
“special character” are not allowed in Content Type Names

### ISSUE THREAD

**Issue by konraplo** [SharePoint/PnP-Sites-Core#795]
Hi
I’m not sure if it’s really bug but I decided to reported as an issue;)

Since Localizations are supported only for SharePoint Online or SharePoint2016,
I used to put in my PnP Template in Content Types/Fields names something like that:
“$Resources:MyResx,MyTextCol”. MyResx are already deployed on SP Farm. 
Now when I try to provision my templates I have got exception in web.ApplyProvisioningTemplate that “special character” are not allowed in Content Type Names. Is there any other way (proper) to put resx into Content Type Names in SharePoint2013 on Prem version?

•PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core 

Category

[x ] Bug
 [ ] Enhancement

Environment

[ ] Office 365 / SharePoint Online
 [ ] SharePoint 2016
 [ x] SharePoint 2013

Expected or Desired Behavior

It should be possible to provision Content Type names with resource keys.

Observed Behavior

If I use in Content Type Names "$Resources:MyResx,MyTextCol", I have got exception by ApplyProvisionigTemplate Method.

Steps to Reproduce

Create and provision a template with Content Type Name="$Resources:MyResx,MyTextCol". Try to provisioning template.

KR
 Konrad

**Comment by erwinvanhunen** [comment]
Hi! Unfortunately this error is not something we can control. The error message is thrown by the server/CSOM API. A workaround for this issue is that you use the resource functionality of our engine: add references of your resource files to the template, and then add a PnP Provisioning Resource token to it. See this blog post for more information on how to use it: http://www.erwinmcm.com/multilingual-provisioning-templates-with-the-office-365-developer-patterns-and-practices-provisioning-engine/.
