### ISSUE TITLE
WillProvision for the ObjectSiteSecurity gets set to false when the site 

### ISSUE THREAD

**Issue by neilstarr** [SharePoint/PnP-Sites-Core#845]
@erwinvanhunen 

#### Category
[* ] Bug
[ ] Enhancement

#### Environment
[* ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Navigation that is specified in the template should get applied to  a sub-site where break role inheritance not true. 

#### Observed Behavior
When attempting to apply security to a sub-site that does not have UniqueRoleAssignments set then WillProvision for ObjectSiteSecurity will always get set to false meaning security can not be provisioned.

The inner if statement causes the problem:
```
if (_willProvision == true)
{
    // if not subweb and site inheritance is not broken
    if (web.IsSubSite() && web.EnsureProperty(w => w.HasUniqueRoleAssignments) == false) 
    {
        _willProvision = false;
    }
}
```

I'm not sure what it is trying to do but going by the comment the if statement should maybe be:

```
if (!web.IsSubSite() && !web.EnsureProperty(w => w.HasUniqueRoleAssignments)
{...}
```

#### Steps to Reproduce
Create a sub-site that does not break role inheritance. Create a template that has some security settings and attempt to apply this template to the sub-site.

**Comment by jansenbe** [comment]
Hi @neilstarr 

We recently added a change so that now the we break role inheritance when a sub site is provisioned and when this is specified in the template like shown below:

```XML
  <pnp:Security ClearSubscopes="false" BreakRoleInheritance="true" >
```

This change will be included in the Feb 2017 release which we'll get out soon. Will close this issue now, but don't hesitate to re-open in case you can't realize your scenario with the Feb 2017 or later releases.
