### ISSUE TITLE
Security settings not provisioned for subsite

### ISSUE THREAD

**Issue by NormanMann** [SharePoint/PnP-Sites-Core#892]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Applying the provisioning template should break inheritance for the subsite where it is applied 

#### Observed Behavior
Inheritance is not broken, group(s) are not created

#### Steps to Reproduce
Create subsite
Use Pnp PowerShell cmdlet Apply-SPOProvisioningTemplate -Path xmlFile (no additional Parameters)

[Security.xml.txt](https://github.com/SharePoint/PnP-Sites-Core/files/642508/Security.xml.txt)

**Comment by jansenbe** [comment]
Hi @NormanMann ,

We recently added a change so that now the we break role inheritance when a sub site is provisioned and when this is specified in the template like shown below:

```XML
  <pnp:Security ClearSubscopes="false" BreakRoleInheritance="true" >
```

This change will be included in the Feb 2017 release which we'll get out soon. Will close this issue now, but don't hesitate to re-open in case you can't realize your scenario with the Feb 2017 or later releases.
