### ISSUE TITLE
AddJsLink - CustomAction ScriptLink render option

### ISSUE THREAD

**Issue by showenx** [SharePoint/PnP-Sites-Core#963]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug
[x ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
pnp core offers options to refer js link as script tag format.

#### Observed Behavior
for PnP Core solution, in JavaScriptExtensions class,  function AddJsLink, currently the javascript reference is implemented via dynamic loading using js

```
scripts.Append(@"
if (scriptsSrc.indexOf('{1}') === -1)  {  
    var newScript = document.createElement('script');
    newScript.id = '{0}';
    newScript.type = 'text/javascript';
    newScript.src = '{1}';
    headID.appendChild(newScript);
    scriptsSrc.push('{1}');
}".Replace("{0}", key).Replace("{1}", link));
```
is it possible to have an option to render the js reference in traditional way as a script tag
`<script type='text/javascript' src='[ref_url]'></script>`

**Comment by erwinvanhunen** [comment]
Hi! Unfortunately not, right now.

We use a CustomAction of type ScriptBlock behind the scenes. I will however modify the code to use a customaction of type ScriptLink if you inject one URL at a time (the methods however take a collection of URL, allowing you inject multiple JS files in one go). If you only inject one, the link will then show up as 

```html
<script type='text/javascript' src='url'><script>
```

You can use the sequence property to define the order of the various links if you insert them separate. 
If you inject multiple links at the same time, e.g. you specify a collection of links, we will fallback to the current way to inject the javascript links with dynamic loading, as this creates a single artifact (= the customaction). As each custom action has a unique name we otherwise would have to generate unique names for each link/customaction we inject, resulting in that you would have to query, or 'assume', what the names of the custom actions are in case you want to remove them. 

I will update this post the moment I have merged it. The functionality will be available in the February 2017 release.

**Comment by erwinvanhunen** [comment]
I now merged PR #972 which solves this. I will close this issue.

**Comment by showenx** [comment]
thanks a lot, the single js ref looks promising, looking forward for the next release.

**Comment by showenx** [comment]
I might post the message on the other issue too.

Thanks a lot for fixing this issue in SharePoint online, can we please also have this fix applied in SharePoint 2013, 2016 PnP-PowerShell?

thanks,
Shawn
